name: Luanti Blog
description: Luanti's official blog - see what's new in Luanti!
author: Luanti
permalink: pretty
# TODO blog.luanti.org once celeron makes it work
url: https://blog.minetest.net

exclude:
  - vendor

excerpt_separator: <!-- more -->

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

collections:
  my_tags:
    output: true
    permalink: /tags/:slug/
